-- Remove FUTBOL_SALA (same as FUTSAL) from SportType ENUM
UPDATE Tournament SET sportType = 'FUTSAL' WHERE sportType = 'FUTBOL_SALA';

ALTER TABLE Tournament MODIFY COLUMN sportType ENUM('FUTBOL_11','FUTSAL','FUTBOL_7','BALONMANO','BALONCESTO','VOLEY','VOLEY_PLAYA','TENIS_MESA','TENIS','BEACH_TENNIS','AJEDREZ','ATLETISMO','DEPORTE_GENERICO','DISPAROS','BATTLE_ROYALE','MOBA_LOL','MOBA_DOTA') NOT NULL DEFAULT 'FUTBOL_11';
